#spring.main.allow-bean-definition-overriding=true
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - "qa"
  application:
    name: accounts
  jpa:
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
  info:
    env:
      enabled: true
  tracing:
    sampling:
          probability: 1.0
info:
  message: "welcome to accounts application default profile"
  name: "raj default profile accounts"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html