spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\Rohit K Verma\OneDrive\Desktop/configfiles
          clone-on-start: true
          default-label: master
server:
  port: 8071
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
